// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "your-email@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/classification": {
            "get": {
                "description": "获取所有支出分类，按树形结构返回",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "支出分类"
                ],
                "summary": "获取支出分类树",
                "responses": {
                    "200": {
                        "description": "成功返回分类树",
                        "schema": {
                            "$ref": "#/definitions/model.Response-array_service_TreeNodeDTO"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/model.Response-any"
                        }
                    }
                }
            },
            "put": {
                "description": "替换数据库中的所有支出分类数据，前端传入完整的树结构",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "支出分类"
                ],
                "summary": "更新整个支出分类树",
                "parameters": [
                    {
                        "description": "分类树数据",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateTreeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/model.Response-bool"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/model.Response-any"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/model.Response-any"
                        }
                    }
                }
            }
        },
        "/export": {
            "post": {
                "description": "接收 JSON 数组，生成并以附件形式下载 Excel 文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "导出"
                ],
                "summary": "导出 Excel",
                "parameters": [
                    {
                        "description": "导出数据列表",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.ExportItem"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Excel 文件（.xlsx）",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/model.Response-bool"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/model.Response-bool"
                        }
                    }
                }
            }
        },
        "/income-classification": {
            "get": {
                "description": "获取所有收入分类，按树形结构返回",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "收入分类"
                ],
                "summary": "获取收入分类树",
                "responses": {
                    "200": {
                        "description": "成功返回分类树",
                        "schema": {
                            "$ref": "#/definitions/model.Response-array_service_TreeNodeDTO"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/model.Response-any"
                        }
                    }
                }
            },
            "put": {
                "description": "替换数据库中的所有收入分类数据，前端传入完整的树结构",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "收入分类"
                ],
                "summary": "更新整个收入分类树",
                "parameters": [
                    {
                        "description": "分类树数据",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateTreeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/model.Response-bool"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/model.Response-any"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/model.Response-any"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "上传 GB2312/GBK 编码的 CSV 文件，自动转码后解析并返回数据行列表",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "上传"
                ],
                "summary": "上传 CSV 文件（GB2312 编码）",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV 文件（GB2312 编码）",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "解析后的数据行列表",
                        "schema": {
                            "$ref": "#/definitions/model.Response-array_array_string"
                        }
                    },
                    "400": {
                        "description": "文件获取或解析失败",
                        "schema": {
                            "$ref": "#/definitions/model.Response-bool"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/model.Response-bool"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ExportItem": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "amount": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.Response-any": {
            "type": "object",
            "required": [
                "code",
                "data",
                "msg",
                "success"
            ],
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "model.Response-array_array_string": {
            "type": "object",
            "required": [
                "code",
                "data",
                "msg",
                "success"
            ],
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "model.Response-array_service_TreeNodeDTO": {
            "type": "object",
            "required": [
                "code",
                "data",
                "msg",
                "success"
            ],
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.TreeNodeDTO"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "model.Response-bool": {
            "type": "object",
            "required": [
                "code",
                "data",
                "msg",
                "success"
            ],
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "service.TreeNodeDTO": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.TreeNodeDTO"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.UpdateTreeRequest": {
            "type": "object",
            "required": [
                "tree"
            ],
            "properties": {
                "tree": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.TreeNodeDTO"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5200",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "账本系统 API",
	Description:      "账本管理系统的后端 API 接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
